# image will be published to ghcr.io/<user>/<name>
name: Valinor
# description will be included in the image's metadata
description: Angelo Piazza's custom linux desktop container image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # dx packages
      - android-tools
      - bcc
      - code
      - devpod
      - docker-ce
      - docker-ce-cli
      - flatpak-builder
      - genisoimage
      - git-credential-libsecret
      - nicstat
      - podman-compose
      - podman-tui
      - podmansh
      - sysprof
      - udica
      - ydotool
      # fonts
      - adobe-source-code-pro-fonts
      - cascadia-code-fonts
      - google-droid-sans-mono-fonts
      - google-go-mono-fonts
      - mozilla-fira-mono-fonts
      - powerline-fonts
      - ubuntu-family-fonts
      
    remove:
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - krb5-workstation
      - printer-driver-brlaser
      - restic
      - samba-dcerpc
		  - samba-ldb-ldap-modules
			- samba-winbind-clients
		  - samba-winbind-modules
			- samba

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
       - com.bitwarden.desktop
       - com.google.Chrome
       - dev.vencord.Vesktop
       - org.gimp.GIMP
       - org.onlyoffice.desktopeditors
       - uk.org.greenend.chiark.sgtatham.putty
       - me.iepure.devtoolbox
       - com.usebottles.bottles
       - com.valvesoftware.Steam
       - com.spotify.Client
       
      remove:
       - org.kde.kontact
       - org.kde.haruna
       - org.fkoehler.KTailctl
       - org.gnome.DejaDup

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

